version: '3'

services:
  zeppelin:
    image: ${ZEPPELIN_IMAGE_NAME:-newfrontdocker/zeppelin-spark:0.9.0-spark3.1.2}
    hostname: zeppelin-spark
    container_name: zeppelin-spark
    networks:
      - mde
    volumes:
      - ${ZEPPELIN_ROOT_DIRECTORY}/notebook:/notebook
      - ${ZEPPELIN_ROOT_DIRECTORY}/logs:/logs
    healthcheck:
      interval: 5s
      timeout: 20s
      retries: 10
    environment:
      - JAVA_HOME=/opt/openjdk-11
      - SPARK_HOME=/opt/spark
      - SPARK_SUBMIT_OPTIONS=--jars=/opt/spark/user_jars/mariadb-java-client-2.7.2.jar --driver-library-path=/opt/spark/user_jars/mariadb-java-client-2.7.2.jar
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - ZEPPELIN_ADDR=0.0.0.0
      - ZEPPELIN_SPARK_MAXRESULT=10000
      - ZEPPELIN_INTERPRETER_OUTPUT_LIMIT=204800
      - ZEPPELIN_NOTEBOOK_COLLABORATIVE_MODE_ENABLE=false
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-minio}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-minio_admin}
    ports:
      - 8080:8080
      - 4040:4040
    restart: always
    depends_on:
      mysql:
        condition: service_started
      minio:
        condition: service_healthy
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${DATA_ENGINEERING_BASEDIR}/mysql/data/mysqldir:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=dataeng
      - MYSQL_PASSWORD=dataengineering_user
      - MYSQL_ROOT_PASSWORD=dataengineering
    healthcheck:
      interval: 5s
      retries: 10
    ports:
      - 3306:3306
    networks:
      - mde
    hostname: mysql
    restart: always
  minio:
    image: minio/minio:latest
    volumes:
      - ${DATA_ENGINEERING_BASEDIR}/minio/data:/data
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio_admin
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 20s
      retries: 3
    ports:
      - 9000:9000
    networks:
      - mde
    hostname: minio
    restart: always

networks:
  mde:
    external: true
    name: mde
