apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spark-apps
  name: spark-app-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - list
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: spark-app-controller-binding
  namespace: spark-apps

subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: spark-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-app-controller