apiVersion: v1
kind: PersistentVolume
metadata:
  name: general-pv-volume
  labels:
    type: local
  namespace: data-services
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/local/data/redis"