apiVersion: v1
kind: Pod
metadata:
  name: redis-basic
  namespace: data-services
  labels:
    app: redis
    type: basic
spec:
  restartPolicy: OnFailure
  containers:
  - name: redis
    image: redis:6.2
    imagePullPolicy: Always
    ports:
    - containerPort: 6379
      protocol: TCP
    resources:
      limits:
        memory: "1G"
        cpu: "2000m"
      requests:
        memory: "500Mi"
        cpu: "1000m"
