apiVersion: v1
kind: Pod
metadata:
  name: debugger
  namespace: spark-apps
  labels:
    app: debugger
spec:
  restartPolicy: OnFailure
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: Always
      command: ["tail", "-f", "/dev/null"]
      resources:
        limits:
          memory: "500Mi"
          cpu: "500m"
        requests:
          memory: "250Mi"
          cpu: "250m"
    